// Remember to keep this list sorted.
export const CLOCK_NAMES = [
  "Flip",
  "Neon Pie",
  "Nixie",
  "Word",
  "Lorem",
  "Ipsum",
  "Sit Amet",
  "Consectetur",
  "Adipiscing",
  "Elit",
  "Sed",
  "Do",
  "Eiusmod",
  "Tempor",
  "Incididunt",
  "Ut",
  "Labore",
  "Et",
  "Dolore",
  "Magna",
  "Aliqua",
  //   "02 Elit",
  //   "02 Sed",
  //   "02 Do",
  //   "02 Eiusmod",
  //   "02 Tempor",
  //   "02 Incididunt",
  //   "02 Ut",
  //   "02 Labore",
  //   "02 Et",
  //   "02 Dolore",
  //   "02 Magna",
  //   "02 Aliqua",
] as const;
